menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/geniustanley
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: geniustanley
duoshuo:

# Analytics
# google-analytics:
ga: UA-91330174-1

# Copyright Infomation
startyear: 2017
