menu:
    Blog: /blog
    Archive: /blog/archives/
    GitHub: https://github.com/carlosmachel
    Rss: /atom.xml

favicon: /favicon.ico
logo: /logo.png

# Comment
disqus: carlosmachel

# Analytics
# google-analytics:
#ga:

# Copyright Infomation
startyear: 2017
